version: '3'

services:
  portainer:
    image: portainer/portainer
    labels:
      - "ops.project=ops"
      - "traefik.enable=true"
      - "traefik.docker.network=ops_gateway"
    userns_mode: "host"
    networks:
      - gateway
    command: --no-auth --host=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data

  apache:
    image: ${OPS_DOCKER_APACHE_IMAGE}
    labels:
      - "ops.project=ops"
      - "traefik.enable=true"
      - "traefik.docker.network=ops_gateway"
      - "traefik.frontend.rule=HostRegexp:localhost,{subdomain:[a-z0-9-]+}.${OPS_DOMAIN}"
      - "traefik.frontend.priority=1"
      - "traefik.port=80"
    environment:
      - APACHE_UID=${OPS_DOCKER_UID}
      - APACHE_GID=${OPS_DOCKER_GID}
      - OPS_DOMAIN=${OPS_DOMAIN}
      - OPS_ENABLED=1
      - OPS_SITES_DIR=${OPS_SITES_DIR}
      - OPS_VERSION=${OPS_VERSION}
    networks:
      - gateway
      - backend
    volumes:
      - ${OPS_HOME}/www/dashboard:/var/www/dashboard
      - ${OPS_HOME}/apache/apache.conf:/etc/apache2/sites-enabled/000-default.conf
      - ${OPS_HOME}/apache/configure:/usr/local/bin/docker-configure
      - ${OPS_HOME}/apache/set_docroot.lua:/etc/apache2/set_docroot.lua
      - ${OPS_SITES_DIR}:/var/www/html:cached

  traefik:
    image: traefik:latest
    command: --docker.domain=${OPS_DOMAIN}
    networks:
      - gateway
    userns_mode: 'host'
    labels:
      - "ops.project=ops"
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${OPS_HOME}/traefik/traefik.dev.toml:/etc/traefik/traefik.toml
      - ${OPS_HOME}/certs/self-signed-cert.crt:/etc/traefik/self-signed-cert.crt
      - ${OPS_HOME}/certs/self-signed-cert.key:/etc/traefik/self-signed-cert.key
      - ${OPS_HOME}/traefik/acme.json:/etc/traefik/acme/acme.json

  minio:
    image: minio/minio
    labels:
      - "ops.project=ops"
      - "traefik.enable=true"
      - "traefik.docker.network=ops_gateway"
      - "traefik.port=80"
    command: server --address ":80" /data
    environment:
      - "MINIO_ACCESS_KEY=${OPS_MINIO_ACCESS_KEY}"
      - "MINIO_SECRET_KEY=${OPS_MINIO_SECRET_KEY}"
    networks:
      - gateway
      - backend
    volumes:
      - minio:/data

  mailhog:
    image: mailhog/mailhog
    labels:
      - "ops.project=ops"
      - "traefik.port=8025"
      - "traefik.enable=true"
      - "traefik.docker.network=ops_gateway"
    networks:
      - gateway
      - backend

  redis:
    image: "redis:3.2"
    ports:
      - "6379:6379"
    labels:
      - "ops.project=ops"
    networks:
      - backend

  memcached:
    image: "memcached:1.4"
    ports:
      - "11211:11211"
    labels:
      - "ops.project=ops"
    networks:
      - backend

  postgres:
    image: "postgres:9.6"
    environment:
        PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
      - backend
    labels:
      - "ops.project=ops"
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data/pgdata"

  mariadb:
    image: "mariadb:10.3"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
    networks:
      - backend
    labels:
      - "ops.project=ops"
    ports:
      - "3306:3306"
    volumes:
      - "mariadb:/var/lib/mysql"

  adminer:
    image: "clue/adminer"
    networks:
      - backend
      - gateway
    labels:
      - "ops.project=ops"
      - "traefik.enable=true"
      - "traefik.docker.network=ops_gateway"

networks:
  gateway:
  backend:

volumes:
  minio:
  portainer:
  postgres:
  mariadb:
