defaultEntryPoints = ["https","http"]
logLevel = "DEBUG"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[retry]

[web]
readOnly = true
users = ["admin:$apr1$vtw10abf$o.4QTNi9t2qXOV6GazY3U."]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "jukebot.live"
watch = true
exposedbydefault = false

[acme]
email = "jeff.turcott@gmail.com"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true
